[package]
name = "hank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
extism = { git = "https://github.com/extism/extism.git", version = "1.0.0-alpha.0" }
extism-pdk = "0.3.4"
futures = "0.3.28"
serde = "1.0.188"
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["macros", "signal", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
twilight-cache-inmemory = "0.15.4"
twilight-gateway = "0.15.4"
twilight-http = "0.15.4"
twilight-model = "0.15.4"
